language: node_js
node_js:
- 'node'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
  - mjr127@case.edu
script:
- npm run build
- npx chromatic test
# blocklist
branches:
  except:
  - l10n_master
